POINTS_TABLE = {1: 10, 2: 6, 3: 4, 4: 3, 5: 2, 6: 1}
MAX_CRASH_OUTS = 5
PLAYER_QUALIFYING_WEAR_INCREASE = 2
PLAYER_RACE_WEAR_INCREASE = 8
PLAYER_FAILURE_PROB_PER_WEAR = 0.002
PLAYER_MAX_FAILURE_PROBABILITY = 0.35
AI_MECHANICAL_FAILURE_PROBABILITY = 0.05
MAX_CAR_WEAR = 100
GRID_JITTER_RANGE_MS = 450
QUALIFYING_ATTEMPTS = 3
QUALIFYING_JITTER_RANGE_MS = 220
QUALIFYING_REDUCTION_CAP_MS_BY_STAR = {
    1: 0,
    2: 50,
    3: 100,
    4: 170,
    5: 240,
}
PACE_CENTER = 50
DRIVER_PACE_MS_PER_POINT = 2000 / 99
CAR_PACE_MS_PER_POINT = 5000 / 99
QUALIFYING_DRIVER_PACE_FACTOR = 0.9
CONSISTENCY_MIN_LAP_PENALTY_MAX_MS = 250
CONSISTENCY_MAX_LAP_PENALTY_MAX_MS = 500
TOTAL_RACE_FUEL_KG = 155.0
FUEL_PENALTY_MS_PER_KG = 30.0
TYRE_DEGRADATION_MS_PER_LAP = 35
TYRE_GRIP_MAX_EFFECT_MS = 1_200
TYRE_WEAR_MAX_MULTIPLIER_DELTA = 0.4
TYRE_COMPOUND_GRIP_RATING_BASELINES = {
    "Hard": 62,
    "Medium": 72,
    "Soft": 82,
}
TYRE_COMPOUND_WEAR_RATING_BASELINES = {
    "Hard": 86,
    "Medium": 72,
    "Soft": 58,
}
TYRE_COMPOUND_STIFFNESS_RATING_BASELINES = {
    "Hard": 82,
    "Medium": 62,
    "Soft": 42,
}
TYRE_COMPOUND_QUALITY_REFERENCE = 75
TYRE_COMPOUND_GRIP_CLASS_EFFECT_MS = {
    "Hard": 300,
    "Medium": 0,
    "Soft": -300,
}
TYRE_COMPOUND_GRIP_QUALITY_MS_PER_POINT = 10
TYRE_COMPOUND_WEAR_CLASS_MULTIPLIER = {
    "Hard": 0.8,
    "Medium": 1.0,
    "Soft": 1.2,
}
TYRE_COMPOUND_WEAR_QUALITY_MULTIPLIER_DELTA = 0.35
PIT_LANE_TIME_LOSS_MS = 25_000
PIT_STRATEGY_WEIGHTS = ((1, 0.45), (2, 0.4), (3, 0.15))
DIRTY_AIR_GAP_THRESHOLD_MS = 1_500
DIRTY_AIR_LAP_PENALTY_MS = 500
OVERTAKE_SUCCESS_PROBABILITY = 0.65
ENGINE_POWER_MAX_EFFECT_MS = 2_000
GRID_SLOT_DISTANCE_M = 5.0
AVERAGE_T1_SPEED_MPS = 47.0
START_SPEED_JITTER_MPS = 1.5
START_DRIVER_SPEED_FACTOR_MPS = 0.06
START_CAR_SPEED_FACTOR_MPS = 0.02
LAP1_SPREAD_BASE_MS = 120
LAP1_SPREAD_JITTER_MS = 80
TURN_ONE_BASE_INCIDENT_PROBABILITY = 0.30
TURN_ONE_COMPRESSION_THRESHOLD_MS = 180
TURN_ONE_COMPRESSION_RISK_PER_CLOSE_PAIR = 0.05
TURN_ONE_MAX_INCIDENT_PROBABILITY = 0.55
TURN_ONE_MAJOR_INCIDENT_PROBABILITY = 0.12
